<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>register</title>
</head>
<body>

<form action="/views/register" method="post">
    <label for="login">LOGIN</label><br>
    <input type="text" name="login"><br><br>

    <label for="email">EMAIL</label><br>
    <input type="email" name="email"><br><br>

    <label for="password">PASSWORD</label><br>
    <input type="password" name="password"><br><br>

    <input type="submit" value="register">
</form>

</body>
</html>