<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

<h1 style="color: indianred">try to make login, email & password > 8 symbol</h1>

<form action="/registration" method="post"><br>
    <label for="login">LOGIN</label><br>
    <input type="text" name="login"><br><br>

    <label for="email">EMAIL</label><br>
    <input type="email" name="email"><br><br>

    <label for="password">PASSWORD</label><br>
    <input type="password" name="password"><br><br>

    <input type="submit" value="REGISTER">
</form>

</body>
</html>