<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

<form action="/login" method="post"><br>
    <label for="username">LOGIN OR EMAIL</label><br>
    <input type="text" name="username"><br><br>

    <label for="password">PASSWORD</label><br>
    <input type="password" name="password"><br><br>

    <input type="submit" value="LOGIN">
</form>

</body>
</html>